<a href="https://colab.research.google.com/github/Shashwat-gla/Python_Assignment/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas Data Structure
# Handling values
# Data Transformation
# String Manupulation

In [2]:
import pandas as pd
import numpy as np

In [4]:
# Create your own dataset
data = {
    'student_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],

    'name': ['Rahul kumar', 'amit sharma', 'PRIYA SINGH', 'Neha veram','Rvai verma', 'ravi kumar', 'Rvai Kumar', 'anjali gupta','vikas singh', 'POOJA SHARMA', 'Karan Metha', 'Arjun Singh','Riya Veram'],

    'Gender': ['Male', 'male', 'female', 'female', 'male', 'female', 'male','female', 'male', 'female', 'male', 'female', 'male'],

    'Department': ['cse', 'cse', 'ece', 'cse', 'ece', 'cse', 'ece','cse', 'me', 'cse', 'cse', 'ece', 'cse'],

    'age': [ 20, 21, np.nan, 75, 88, 65, 92, np.nan, 70, 95, 80, np.nan, 22],

    'Attendance': [85, 78, np.nan, 90 , 75, 88, 65, 92, np.nan, 70, 95, 80, np.nan],

    'Marks': [85, 72, np.nan, 75, 88, 65, 92, np.nan, 76, 64, 95, 81, 78 ],

    'Email': ['rahul@gmail.com', 'amit@gamil.com', 'priya@gmail','neha@gmail.com', 'None', 'anjali@gmail', 'vikas@gmail.com','pooja@gmail.com', 'vikas@gmail.com', 'pooja@gmail.com','karan@gmail.com', 'arjun@gmail.com', 'riya@gmail.com']
}
df = pd.DataFrame(data)
display(df)

,student_ID,name,Gender,Department,age,Attendance,Marks,Email
0,101,Rahul kumar,Male,cse,20.0,85.0,85.0,rahul@gmail.com
1,102,amit sharma,male,cse,21.0,78.0,72.0,amit@gamil.com
2,103,PRIYA SINGH,female,ece,NaN,NaN,NaN,priya@gmail
3,104,Neha veram,female,cse,75.0,90.0,75.0,neha@gmail.com
4,105,Rvai verma,male,ece,88.0,75.0,88.0,None
5,106,ravi kumar,female,cse,65.0,88.0,65.0,anjali@gmail
6,107,Rvai Kumar,male,ece,92.0,65.0,92.0,vikas@gmail.com
7,108,anjali gupta,female,cse,NaN,92.0,NaN,pooja@gmail.com
8,109,vikas singh,male,me,70.0,NaN,76.0,vikas@gmail.com
9,110,POOJA SHARMA,female,cse,95.0,70.0,64.0,pooja@gmail.com
10,111,Karan Metha,male,cse,80.0,95.0,95.0,karan@gmail.com
11,112,Arjun Singh,female,ece,NaN,80.0,81.0,arjun@gmail.com
12,113,Riya Veram,male,cse,22.0,NaN,78.0,riya@gmail.com

In [7]:
print('Shape:',df.shape)
print('columns:',df.columns.tolist)
print('Data Types ', df.dtypes)
display(df.head())
display(df.tail())

Shape: (13, 8)
columns: <bound method IndexOpsMixin.tolist of Index(['student_ID', 'name', 'Gender', 'Department', 'age', 'Attendance',
       'Marks', 'Email'],
      dtype='object')>
Data Types  student_ID      int64
name           object
Gender         object
Department     object
age           float64
Attendance    float64
Marks         float64
Email          object
dtype: object

,student_ID,name,Gender,Department,age,Attendance,Marks,Email
0,101,Rahul kumar,Male,cse,20.0,85.0,85.0,rahul@gmail.com
1,102,amit sharma,male,cse,21.0,78.0,72.0,amit@gamil.com
2,103,PRIYA SINGH,female,ece,NaN,NaN,NaN,priya@gmail
3,104,Neha veram,female,cse,75.0,90.0,75.0,neha@gmail.com
4,105,Rvai verma,male,ece,88.0,75.0,88.0,None

,student_ID,name,Gender,Department,age,Attendance,Marks,Email
8,109,vikas singh,male,me,70.0,NaN,76.0,vikas@gmail.com
9,110,POOJA SHARMA,female,cse,95.0,70.0,64.0,pooja@gmail.com
10,111,Karan Metha,male,cse,80.0,95.0,95.0,karan@gmail.com
11,112,Arjun Singh,female,ece,NaN,80.0,81.0,arjun@gmail.com
12,113,Riya Veram,male,cse,22.0,NaN,78.0,riya@gmail.com

In [10]:
 # Detect Missing values
print(df.isnull().sum())

student_ID    0
name          0
Gender        0
Department    0
age           3
Attendance    3
Marks         2
Email         0
dtype: int64

In [13]:
# Handle the missing values

df['age'] = df['age'].fillna(df['age'].mean())
df['Attendance'] = df['Attendance'].fillna(df['Attendance'].mean())
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
df['Email'] = df['Email'].fillna('Not Provided')

# Check remaining missing values
print(df.isnull().sum())

student_ID    0
name          0
Gender        0
Department    0
age           0
Attendance    0
Marks         0
Email         0
dtype: int64

In [16]:
# data Trnsformation
df['Reslut ']=df['Marks'].apply(lambda x: 'Pass' if x >= 75 else 'Fail')
def assign_grade(marks):
    if marks >= 80:
        return 'A'
    elif marks >= 60:
        return 'B'
    elif marks >= 40:
        return 'C'
    else:
        return 'F'
df['Grade'] = df['Marks'].apply(assign_grade)
display(df)

,student_ID,name,Gender,Department,age,Attendance,Marks,Email,Reslut,Grade
0,101,Rahul kumar,Male,cse,20.0,85.0,85.000000,rahul@gmail.com,Pass,B
1,102,amit sharma,male,cse,21.0,78.0,72.000000,amit@gamil.com,Fail,C
2,103,PRIYA SINGH,female,ece,62.8,81.8,79.181818,priya@gmail,Pass,C
3,104,Neha veram,female,cse,75.0,90.0,75.000000,neha@gmail.com,Pass,C
4,105,Rvai verma,male,ece,88.0,75.0,88.000000,None,Pass,B
5,106,ravi kumar,female,cse,65.0,88.0,65.000000,anjali@gmail,Fail,D
6,107,Rvai Kumar,male,ece,92.0,65.0,92.000000,vikas@gmail.com,Pass,A
7,108,anjali gupta,female,cse,62.8,92.0,79.181818,pooja@gmail.com,Pass,C
8,109,vikas singh,male,me,70.0,81.8,76.000000,vikas@gmail.com,Pass,C
9,110,POOJA SHARMA,female,cse,95.0,70.0,64.000000,pooja@gmail.com,Fail,D
10,111,Karan Metha,male,cse,80.0,95.0,95.000000,karan@gmail.com,Pass,A
11,112,Arjun Singh,female,ece,62.8,80.0,81.000000,arjun@gmail.com,Pass,B
12,113,Riya Veram,male,cse,22.0,81.8,78.000000,riya@gmail.com,Pass,C